Pr 19 CI on DB branch
digitalbazaar/vc-revocation-list pull request #23
Opened 2020-08-11 03:11 UTC by mattcollier

2020-08-11 03:13 UTC, mattcollier commented
Linting errors are preventing CI from running.  I'll fix that up tomorrow.

2020-08-11 13:34 UTC, mattcollier commented
Hello @kdenhartog thanks again for the PR. I fixed this up to get CI running here and the tests around this new feature are failing.  Is the test suite passing for you on this branch?  It appears to me that the issuers on the RL credential and the credential are in fact the same value `did:example:123`.

See: https://github.com/digitalbazaar/vc-revocation-list/runs/971373437?check_suite_focus=true

2020-09-07 02:30 UTC, kdenhartog requested changes
Looks like this won't work for node 10 either because the package.json file sets the node environment to be >12.0.0. When I set [this line](https://github.com/digitalbazaar/vc-revocation-list/blob/91723fc1bbe79b79c5d18f487d49a471f0143c22/package.json#L81) to `"node": ">=10.0.0"`

2020-09-07 02:30 UTC, kdenhartog commented on tests/30-main.spec.js
> +      issuer: 'did:example:123',
This can't match the issuer did in the RLC object above. 

```suggestion
      issuer: 'did:example:1234',
```

2021-05-20 15:17 UTC, mattcollier commented
@dlongley @kdenhartog would we want the default behavior to be that the verifiers should be validated?  Change the default `verifyMatchingIssuers` value to `true` and release this is a major breaking change?

2021-05-20 15:39 UTC, dlongley commented
@mattcollier,

> would we want the default behavior to be that the verifiers should be validated? Change the default `verifyMatchingIssuers` value to `true` and release this is a major breaking change?

I'm assuming you meant "issuers" (not "verifiers"). In any case, my first inclination was to say "yes", but my second thought was that it may place an undue burden on certain decentralized use cases. An issuer may want to allow some other entity to handle revocation and publishing revocation VCs. There's nothing that's inherently less trustworthy with non-matching issuers on their own -- it's just a different mode. The question is -- do you trust your resolver to return the RC VC that the original issuer intended you to get (regardless of who signed it)?

My third thought is that we should have the defaults be the strictest they can be since this is a security lib -- and that we may end up needing to have another property in the VC itself (in the revocation section ... or define the behavior according to the credential status type) that specifies whether or not the issuer needs to match.

So, in the end, I'm +1 for requiring the issuers to match by default in this library.

2021-05-20 22:01 UTC, kdenhartog commented
I originally took the approach of defaulting to false in order to not cause breaking changes for this, but I'm happy to see it set to true by default. @dlongley point about this being a security lib is the most compelling reason for me as well.

2021-05-20 22:54 UTC, mattcollier commented
@dlongley @kdenhartog ready for review of breaking release.

2021-05-21 00:20 UTC, kdenhartog approved these changes
Added some suggested updates to the errors to make it a bit more clear what failed. Happy with either though.

2021-05-21 00:20 UTC, kdenhartog commented on main.js
> +      throw new Error('Issuers of the credentials do not match.');
```suggestion
      throw new Error('Issuers of the revocation credential and verifiable credential do not match.');
```

2021-05-21 00:20 UTC, kdenhartog commented on tests/30-main.spec.js
> +      'Issuers of the credentials do not match.');
```suggestion
      'Issuers of the revocation credential and verifiable credential do not match.');
```

2021-05-23 02:07 UTC, dlongley approved these changes

2021-05-24 16:33 UTC, merged